### ISSUE TITLE
Broken link on CLI docs page

### ISSUE THREAD

**Issue by mtabz** [klevoya/docs#3]
In the [Init](https://docs.klevoya.com/hydra/cli/cli/#init) section there's a broken reference to a [JSON fixture files](https://docs.klevoya.com/hydra/cli/examples/initial-contract-tables.md) page which does not exist. Should this refer instead to https://docs.klevoya.com/hydra/guides/initial-contract-tables?

**Comment by MrToph** [comment]
Fixed in a469acba56fdf90170616c20b3510e1b2a81e36c
